name = "vqc_in_lean"
version = "0.1.0"
defaultTargets = ["vqc_in_lean"]

[[lean_lib]]
name = "VqcInLean"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"

[[lean_exe]]
name = "vqc_in_lean"
root = "Main"
